import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnswerStoreProvider } from "@/providers/AnswerProvider";
import { Header } from "@/components/Header/Header";
import { TestStoreProvider } from "@/providers/TestProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
  }: Readonly<{
    children: React.ReactNode;
    }>) {
  const data = await fetch("http://localhost:3000/api/gettests", {
    next: {
      revalidate: 1200,
      tags: ['tests']
    },
    referrer: "http://localhost:3000"
  })
  const tests = await data.json()
  return (
    <html lang="en">
      <body className={inter.className}>
        <TestStoreProvider initialState={tests}>
          <AnswerStoreProvider>
            <Header />
            {children}
          </AnswerStoreProvider>
        </TestStoreProvider>
      </body>
    </html>
  );
}
